MODEL:
    NETWORK: 'lainet'
    WINDOW_SIZE: 500
TRAINING:
    DEVICE: 'cuda'
    OPTIM: 'Adam'
    ALPHA: 0.5
    LEARNING_RATE: 0.01
    WEIGHT_DECAY: 0.0
    BATCH_SIZE: 128
    BALANCED_TYPE: 'Batch'
    ONLINE_SIMULATION_MODE: 'pre-defined'
    ONLINE_SIMULATION_REALISTIC: True
    GENERATION_NUM_LIST: [2, 4, 16, 32, 64]
    RANDOM_TRAINVAL_SPLIT: False
    ITER_BREAK: 10
    DEVICE: 'cuda'
    NUM_EPOCHS: 20000
    SAVE_MODEL: True